### ISSUE TITLE
Audio Overload Plugin for supporting psf, psf2, spu, dsf, ssf, qsf formats.

### ISSUE THREAD

**Issue by Shellcat-Zero** [xmms2/xmms2-devel#1]
Is there any work underway to support these formats?  The Deadbeef project is now able to support them (https://github.com/Alexey-Yakovenko/deadbeef/tree/master/plugins/ao) by adapting the Audio Overload engine (https://github.com/nmlgc/aosdk).  How feasible is this in XMMS2?

**Comment by dsvensson** [comment]
Looks very easy to add. Drop by #xmms2 @ irc.freenode.net if you get stuck. The existing xforms in src/plugins/* should provide guidance to you. Also, this is not the place for feature requests / bugs, disabling the functionality and I hope you get the mail about this reply.
